-- 16 Business Problems

1. How many staffs are active in each stores?

2. Who are managers in each store?

3. Calculate the average bike price for each model year.

4. Which state has the most customers and how many?

5. Provide the number of available products in stocks in each category

6. Show the total number of orders placed as per their order status
   order_status: 1 for Payment Validated, 2 for In Progress, 3 for Prepared for Shipping, and 4 for Shipped.

7. Show the order count for each month in 2016–2018

8. List products with low stock in each store
   Criteria for a product to be low is that its quantity <=2

9. Which store has the most late shipped orders?

10. Calculate the total revenue generated from each product category

11. Determine the average time between order placement and shipment for each city

12. Segment customers based on their purchase history
    Frequent Customers are customers who generate significant revenue through large (spending > $5,000) or frequent purchases (orders > 2).
    Infrequent Customers: Customers who contribute less revenue, making occasional (spending < $4,999) or low priced purchases (orders < 3).

13. Who are the top 3 customers(name, phone, email, total spending) with highest purchases in each state?

14. Rank lowest 2 products of each brands on basis of revenue generated by their products.

15. Determine top 2 staffs in each store who generated the most revenue.

16. Which products are sold out in one store but available in others?
    And also provide quantity of the product in each store?